trigger:
- main

pool:
  name: sample-pool

steps:

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: '**' # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'firstcode'
    publishLocation: 'Container'